//! Opens a link to something outside the app: URLs in the browser (a new tab on
//! the web, the system browser natively). Natively, "Text version" opens the
//! embedded plain HTML page offline and "PDF" prefers the copy shipped next
//! to the executable.

use resume_model::site;

use crate::scene::Link;

/// The plain HTML resume, generated by resume-gen (committed in the repo).
#[cfg(not(target_arch = "wasm32"))]
const PLAIN_HTML: &str = include_str!("../web/plain.html");

pub fn open(link: &Link) {
    if let Err(error) = try_open(link) {
        log::error!("opening {link:?} failed: {error}");
    }
}

#[cfg(target_arch = "wasm32")]
fn try_open(link: &Link) -> Result<(), String> {
    let url = match link {
        Link::Url(url) => url.clone(),
        Link::TextVersion => "plain.html".to_owned(),
        Link::Pdf => site::PDF_FILE.to_owned(),
    };
    crate::web::open_url(&url)
}

#[cfg(not(target_arch = "wasm32"))]
fn try_open(link: &Link) -> Result<(), String> {
    let target = match link {
        Link::Url(url) => url.clone(),
        Link::TextVersion => {
            let path = std::env::temp_dir().join("harald-reingruber-resume.html");
            std::fs::write(&path, PLAIN_HTML).map_err(|e| e.to_string())?;
            path.display().to_string()
        }
        Link::Pdf => std::env::current_exe()
            .ok()
            .and_then(|exe| Some(exe.parent()?.join(site::PDF_FILE)))
            .filter(|path| path.is_file())
            .map_or_else(site::pdf_url, |path| path.display().to_string()),
    };
    open::that_detached(&target).map_err(|e| e.to_string())
}
