//! Performs a clicked link's action: opens URLs in the browser (a new tab on
//! the web, the system browser natively). Natively, "Text version" opens the
//! embedded plain HTML page offline and "PDF" prefers the copy shipped next
//! to the executable.

use resume_model::site;

use crate::scene::Action;

/// The plain HTML resume, generated by resume-gen (committed in the repo).
#[cfg(not(target_arch = "wasm32"))]
const PLAIN_HTML: &str = include_str!("../web/plain.html");

pub fn open(action: &Action) {
    if let Err(error) = try_open(action) {
        log::error!("opening {action:?} failed: {error}");
    }
}

#[cfg(target_arch = "wasm32")]
fn try_open(action: &Action) -> Result<(), String> {
    let url = match action {
        Action::OpenUrl(url) => url.clone(),
        Action::TextVersion => "plain.html".to_owned(),
        Action::Pdf => site::PDF_FILE.to_owned(),
    };
    crate::web::open_url(&url)
}

#[cfg(not(target_arch = "wasm32"))]
fn try_open(action: &Action) -> Result<(), String> {
    let target = match action {
        Action::OpenUrl(url) => url.clone(),
        Action::TextVersion => {
            let path = std::env::temp_dir().join("harald-reingruber-resume.html");
            std::fs::write(&path, PLAIN_HTML).map_err(|e| e.to_string())?;
            path.display().to_string()
        }
        Action::Pdf => std::env::current_exe()
            .ok()
            .and_then(|exe| Some(exe.parent()?.join(site::PDF_FILE)))
            .filter(|path| path.is_file())
            .map_or_else(site::pdf_url, |path| path.display().to_string()),
    };
    open::that_detached(&target).map_err(|e| e.to_string())
}
