//! Opens a link to something outside the app: URLs in the browser (a new tab on
//! the web, the system browser natively). On the desktop, "Text version" opens
//! the embedded plain HTML page offline and "PDF" prefers the copy shipped next
//! to the executable; phone apps open the hosted pages instead.

use resume_model::site;

use crate::scene::Link;

/// The plain HTML resume, generated by resume-gen (committed in the repo).
#[cfg(not(any(target_arch = "wasm32", target_os = "android", target_os = "ios")))]
const PLAIN_HTML: &str = include_str!("../../web/plain.html");

pub fn open(link: &Link) {
    if let Err(error) = try_open(link) {
        log::error!("opening {link:?} failed: {error}");
    }
}

#[cfg(target_arch = "wasm32")]
fn try_open(link: &Link) -> Result<(), String> {
    let url = match link {
        Link::Url(url) => url.clone(),
        Link::TextVersion => "plain.html".to_owned(),
        Link::Pdf => site::PDF_FILE.to_owned(),
    };
    crate::platform::web::open_url(&url)
}

#[cfg(not(any(target_arch = "wasm32", target_os = "android", target_os = "ios")))]
fn try_open(link: &Link) -> Result<(), String> {
    let target = match link {
        Link::Url(url) => url.clone(),
        Link::TextVersion => {
            let path = std::env::temp_dir().join("harald-reingruber-resume.html");
            std::fs::write(&path, PLAIN_HTML).map_err(|e| e.to_string())?;
            path.display().to_string()
        }
        Link::Pdf => std::env::current_exe()
            .ok()
            .and_then(|exe| Some(exe.parent()?.join(site::PDF_FILE)))
            .filter(|path| path.is_file())
            .map_or_else(site::pdf_url, |path| path.display().to_string()),
    };
    open::that_detached(&target).map_err(|e| e.to_string())
}

/// Phones: an app can't hand its sandboxed files to the browser, so the
/// text version and the PDF open the hosted pages.
#[cfg(any(target_os = "android", target_os = "ios"))]
fn try_open(link: &Link) -> Result<(), String> {
    let url = match link {
        Link::Url(url) => url.clone(),
        Link::TextVersion => format!("{}plain.html", site::SITE_URL),
        Link::Pdf => site::pdf_url(),
    };
    open_on_phone(&url)
}

#[cfg(target_os = "android")]
fn open_on_phone(url: &str) -> Result<(), String> {
    crate::platform::android::open_url(url)
}

#[cfg(target_os = "ios")]
fn open_on_phone(url: &str) -> Result<(), String> {
    open::that_detached(url).map_err(|e| e.to_string())
}
